/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class euclidean_Sparccelerator_NativeMethod__ */

#ifndef _Included_euclidean_Sparccelerator_NativeMethod__
#define _Included_euclidean_Sparccelerator_NativeMethod__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     euclidean_Sparccelerator_NativeMethod__
 * Method:    euclidean
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)Ljava/lang/Void;
 */
JNIEXPORT jobject JNICALL Java_euclidean_Sparccelerator_00024NativeMethod_00024_euclidean
  (JNIEnv *, jobject, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
