/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sum_Sparccelerator_NativeMethod__ */

#ifndef _Included_sum_Sparccelerator_NativeMethod__
#define _Included_sum_Sparccelerator_NativeMethod__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sum_Sparccelerator_NativeMethod__
 * Method:    testC
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_sum_Sparccelerator_00024NativeMethod_00024_testC
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
