/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tpchsum_Sparccelerator_NativeMethod__ */

#ifndef _Included_tpchsum_Sparccelerator_NativeMethod__
#define _Included_tpchsum_Sparccelerator_NativeMethod__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tpchsum_Sparccelerator_NativeMethod__
 * Method:    tpchsum
 * Signature: (Ljava/nio/ByteBuffer;II)D
 */
JNIEXPORT jdouble JNICALL Java_tpchsum_Sparccelerator_00024NativeMethod_00024_tpchsum
  (JNIEnv *, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
